title: Google Analytics Tools and Demos
slug: ''
path: '/'
tracking_id: UA-41425441-5
client_id: 793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com

# Google Analytics tech tags. Demos and tools should tag themselves with
# one or more of these to make tech more discoverable.
tech:
  analyticsjs:
    name: analytics.js
    url: https://developers.google.com/analytics/devguides/collection/analyticsjs/
  core_reporting_api:
    name: Core Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/core/
  ecjs:
    name: Enhanced Ecommerce (ec.js)
    url: https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce
  embed_api:
    name: Embed API
    url: https://developers.google.com/analytics/devguides/reporting/embed/
  management_api:
    name: Management API
    url: https://developers.google.com/analytics/devguides/config/mgmt/
  mcf_reporting_api:
    name: MCF Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/mcf/
  measurement_protocol:
    name: Measurement Protocol
    url: https://developers.google.com/analytics/devguides/collection/protocol/
  metadata_api:
    name: Metadata API
    url: https://developers.google.com/analytics/devguides/reporting/metadata/
  provisioning_api:
    name: Provisioning API
    url: https://developers.google.com/analytics/devguides/config/provisioning/
  real_time_reporting_api:
    name: Real Time Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/realtime/

# Links represent external URLs that may frequently change.
# Setting them here makes it easier to update globally.
links:
  devsite: http://developers.google.com/analytics
  github: https://github.com/googleanalytics/ga-dev-tools

projects:
- title: Account Explorer
  type: tool
  slug: account-explorer
  status: new
  tech: [embed_api, management_api]
- title: Dimensions & Metrics Explorer
  type: tool
  slug: dimensions-metrics-explorer
  external: https://developers.google.com/analytics/devguides/reporting/core/dimsmets
  tech: [metadata_api]
- title: Enhanced Ecommerce
  type: demo
  slug: enhanced-ecommerce
  status: new
  external: https://enhancedecommerce.appspot.com
  tech: [analyticsjs, ecjs]
- title: Embed API
  type: demo
  slug: embed-api
  pages:
  - title: Basic Dashboard
    slug: basic-dashboard
    tech: [embed_api]
    excerpt: 'This demos shows how to create a basic dashboard with a single timeline chart showing site traffic over the past week. You can update the chart to see data for any Google Analytics view you have access to.'
  - title: Multiple Date Ranges
    slug: multiple-date-ranges
    tech: [embed_api]
    excerpt: 'Displaying data side-by-side from multipe different date ranges is not currently possible through the Google Analytics website. This demo shows how easy it is to do this using the Embed API.'
  - title: Multiple Views
    slug: multiple-views
    tech: [embed_api]
    excerpt: 'Displaying two different views side-by-side is not currently possible through the Google Analytics website. This demo shows how easy it is to do this using the Embed API.'
  - title: Interactive Charts
    slug: interactive-charts
    tech: [embed_api]
    excerpt: 'This demo shows how you can build a dashboard that allows you to interactively explore your data. In this example you have a list of filters in one chart that you can click on and then a second chart will render showing just that filtered dataset.'
  - title: Working with Custom Components
    slug: custom-components
    tech: [embed_api]
    excerpt: 'The built-in components that ship with the Embed API are very nice, but sometimes you need to do more. This example shows how you can extend the Embed API to use your own custom components.'
  - title: Third Party Visualizations
    slug: third-party-visualizations
    tech: [embed_api, real_time_reporting_api]
    excerpt: 'The Embed API make it easy to query data and display it in a Google Chart. But it also allows you to access the raw data so you can display it however you want. This example uses the <a href="http://www.chartjs.org/">Chart.js</a> visualization library.'
- title: Polymer Elements
  type: demo
  slug: polymer-elements
  external: http://googlewebcomponents.github.io/google-analytics/components/google-analytics/demo.html
  tech: [management_api, metadata_api]
- title: Query Explorer
  type: tool
  slug: explorer
  tech: [core_reporting_api, management_api, metadata_api]
- title: Spreadsheet Add-on
  type: tool
  slug: spreadsheet-add-on
  external: https://chrome.google.com/webstore/detail/google-analytics/fefimfimnhjjkomigakinmjileehfopp
  tech: [core_reporting_api, management_api, mcf_reporting_api, metadata_api]

